server:
  port: 10010
spring:
  application:
    name: da-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
hystrix:
  command:
    dafault:
      execution.isolation.thread.timeoutInMilliseconds: 6000 # 熔断超时时长：6000ms
ribbon:
  ConnectTimeout: 500
  ReadTimeout: 2000
zuul:
  prefix: /api
  routes:
    item-service: /item/**